language: cpp

sudo: false

cache:
- apt
- directories:
  - toolchain
  - $HOME/.local
  - android/sdk
  - $HOME/.gradle

matrix:
  exclude:
    - os: linux
  include:
    - os: linux
      env: FLAVOR=linux CXX=clang++ CC=clang BUILDTYPE=Debug
    - os: linux
      env: FLAVOR=linux CXX=clang++ CC=clang BUILDTYPE=Release
    - os: linux
      env: FLAVOR=linux CXX=g++ CC=gcc BUILDTYPE=Release
    - os: osx
      env: FLAVOR=osx CXX=clang++ CC=clang BUILDTYPE=Debug
    - os: linux
      env: FLAVOR=android ANDROID_ABI=arm-v7 BUILDTYPE=Debug TESTMUNK=no
    - os: linux
      env: FLAVOR=android ANDROID_ABI=arm-v5 BUILDTYPE=Release TESTMUNK=no
    - os: linux
      env: FLAVOR=android ANDROID_ABI=arm-v8 BUILDTYPE=Release TESTMUNK=yes
    - os: linux
      env: FLAVOR=android ANDROID_ABI=x86 BUILDTYPE=Release TESTMUNK=no
    - os: linux
      env: FLAVOR=android ANDROID_ABI=mips BUILDTYPE=Release TESTMUNK=no
    - os: linux
      env: FLAVOR=android ANDROID_ABI=mips-64 BUILDTYPE=Release TESTMUNK=no

env:
  global:
   - secure: "MZHblLZXG/jWf2w0ZFlxCLDwx2qtGgRDODQyg1BR7JIuMz6AtWv8XR/sUczWLbiABCL0a/NzJF1g4v2pI7X69IntcjOdIABBgTh7++6+1TJ0Kp8viEltb55nQG3lHy/R6fOaI7Pj9tuCX0PCRtGA5C/fGnodLGEjy3RVOJ09ln0="
   - secure: "KaSQbhgjtV7ZCkesHmvrNsbQVjk5SPfGKB1VkWenRGYhLF45HpSRNwSxMQddZ566Pg7qIFgF1iWl/B0QW3B6AWL5WmzQ5AOJgwS876pNIc/UT7ubMPtgAtjpvw1bQvQP3B8MrB+3OE5c6tD+a3LhR9krV//dOsfErR5Yy+3Mbkc="
   - secure: "RiBIBfVhhaMjU5ksuwJO3shdvG9FpinBjdSv4co9jg9171SR8edNriedHjVKSIeBhSGNmZmX+twS3dJS/By6tl/LKh9sTynA+ZAYYljkE7jn881B/gMrlYvdAA6og5KvkhV1/0iJWlhuZrMTkhpDR200iLgg3EWBhWjltzmDW/I="
   - secure: "CHBiUM60TolDbQnn+4IRA/tvOKwKs3g9EDvv8YHSJMg3FuHmjKQkprBasvxf3hnTXg4WLZEubmeDcyJ6RRzPP5mMSr/hksYl0pSjj/6TUecE5fHPVVeN7txVqkpOBf9i45Y+iBUQMjBb1NnDK3pHXxpnAs1Q/pe7vReErj4GF1U="
   - TERM: dumb
   # begin iOS code signing
   - secure: "I6Iu75X1E+js5tzijtKi1EGtIuBcA4/25nDYe0svV4HAtujY71ZJZ4eB6355CKhFXpLXrF3i7eKVX3v+zWS0QROPEWacgsqsvNg+Ba9cnznW/faUSOYekCfhzWd/6reYDM7KzKAQwSUHLk9JIWK/kkmi4r+vVJK7h+tjPllK5YA="
   - IOS_APP_NAME="Mapbox GL"
   - 'IOS_DEVELOPER_NAME="iPhone Distribution: Mapbox, Inc."'
   - IOS_PROFILE_NAME="ios-in-house"
   - secure: "nQqSM8rd7OHtV4MqmNqVnkrVHqxKqQsaWRYk4/nPdhbeVWtTtkk0df711LrF1TUtbEPEewHxYUvTZ/UXmwJNeoKdzTHavI8hnatRkgjyxGERPn1il1Otelht9I+LQQHf+plrpRjVWBrNIW0Zox1B3cqn6d3NglpbXrEQ2EjYGNA="
   # end iOS code signing

addons:
  apt_packages:
  - gdb # for printing stack traces from core dumps
  - xutils-dev
  - libxxf86vm-dev
  - x11proto-xf86vidmode-dev
  - mesa-utils # for glxinfo
  - libisl10 # for g++-4.8
  - libcloog-isl4 # for g++-4.8
  - lib32stdc++6 # for Gradle's aapt
  - lib32z1 # for Gradle's aapt
  - expect # for accepting Android SDK licenses

install:
- ./scripts/${FLAVOR}/install.sh

script:
- ./scripts/${FLAVOR}/run.sh

git:
  submodules: false
